import type { AppConfig } from "../src/config";

export function config(overrides: Partial<AppConfig> = {}): AppConfig {
  return {
    upstreams: ["https://primary.example/dns-query", "https://secondary.example/dns-query"],
    ecsUpstreams: ["https://primary.example/dns-query", "https://secondary.example/dns-query"],
    upstreamTimeoutMs: 100,
    upstreamHedgeMs: 0,
    ecsUpstreamHedgeMs: 0,
    cacheMinTtl: 1,
    cacheMaxTtl: 3600,
    negativeCacheMaxTtl: 300,
    cacheStaleTtl: 0,
    cachePrefetchPercent: 0,
    ecsMode: "rules",
    ecsDomains: [".cn"],
    ecsIpv4Prefix: 24,
    ecsIpv6Prefix: 48,
    ecsDomainListUrls: [],
    cnUpstreams: [],
    cnDomains: [],
    resolverViewDomains: [],
    edgeOneClientIpHeader: "EO-Connecting-IP",
    cfRewriteEnabled: false,
    cfPreferredDomains: [],
    cfPreferredIpv4: [],
    cfPreferredIpv6: [],
    cfDropAaaa: false,
    cfRewriteExclude: [".argotunnel.com", ".cftunnel.com", ".cloudflareclient.com"],
    cfIpv4Url: "https://www.cloudflare.com/ips-v4/",
    cfIpv6Url: "https://www.cloudflare.com/ips-v6/",
    rulesJson: "[]",
    echEnabled: false,
    echDomains: [],
    echSourceDomain: "cloudflare-ech.com",
    metaDomains: [],
    xDomains: [],
    githubDomains: [],
    safeListUrls: [],
    safeAllow: [],
    dynamicRuleHosts: ["paste.rs"],
    dynamicRulesMaxBytes: 262144,
    debug: false,
    logQueries: false,
    maxDnsPacketSize: 4096,
    ...overrides,
  };
}
